syntax = "proto3";
option csharp_namespace = "Skyle_Server";

package Skyle.Types;

/**
 * Message for a 2D point
 */
message Point {
  double x = 1;
  double y = 2;
}

/**
 * Message for a size
 */
message Size {
  double width = 1;
  double height = 2;
}

/**
 * Message for a rectangle
 */
message Rectangle {
  Point topLeft = 1;
  Size size = 2;
}

/**
 * Message for a rotated rectangle
 * This rectangle is defined by its center, size, and angle
 * The angle is in degrees, counter-clockwise from the x-axis
 */
message RotatedRectangle {
  Point center = 1;
  Size size = 2;
  double angle = 3;
}

/**
 * Message for a feature
 */
message Feature {
  Point center = 1;             // Center of the feature
  RotatedRectangle ellipse = 2; // Ellipse of the feature
}

/**
 * Left and right glint
 */
message Glints {
  Feature left = 1;  // Left glint
  Feature right = 2; // Right glint
}

/**
 * Message for a gaze
 */
message Gaze {
  Point raw = 1;      // Raw gaze point
  Point smoothed = 2; // Smoothed gaze point
}

/**
 * Message for an eye
 */
message Eye {
  Point keyPoint = 1;         // Roughly estimated key point of the eye
  Feature iris = 2;           // Feature of the iris
  Feature pupil = 3;          // Feature of the pupil
  Glints glints = 4;          // Glints in the eye
  double distance = 5;        // Estimated distance to the camera in mm
  Rectangle boundingRect = 6; // Bounding box of the eye
  Gaze gaze = 7;              // Estimated gaze point of that data set
}

/**
 * Message for a pair of eyes
 */
message Eyes {
  Eye left = 1;  // Left eye
  Eye right = 2; // Right eye
}

/*
 * Message for the head pose
 */
message HeadPose {
  double pitch = 1;
  double yaw = 2;
  double roll = 3;
}

/**
 * Message for a face
 * Rectangle bounding box of the face
 * Eyes containing several features of the eyes
 */
message Face {
  Rectangle boundingRect = 1; // Bounding box of the face
  Eyes eyes = 2;              // Eyes
  bytes id = 3;               // Unique identifier for the face
  HeadPose headPose = 4;
}

/**
 * Single image in grayscale raw bytes
 */
message Mat {
  enum MatType {
    CV_8UC1 = 0;   // 8-bit unsigned, 1 channel (grayscale)
    CV_8UC3 = 1;   // 8-bit unsigned, 3 channels (BGR color)
    CV_8UC4 = 2;   // 8-bit unsigned, 4 channels (BGRA color)
    CV_16UC1 = 3;  // 16-bit unsigned, 1 channel
    CV_16UC3 = 4;  // 16-bit unsigned, 3 channels
    CV_16UC4 = 5;  // 16-bit unsigned, 4 channels
    CV_32FC1 = 6;  // 32-bit float, 1 channel
    CV_32FC3 = 7;  // 32-bit float, 3 channels
    CV_32FC4 = 8;  // 32-bit float, 4 channels
    CV_64FC1 = 9;  // 64-bit float, 1 channel
    CV_64FC3 = 10; // 64-bit float, 3 channels
    CV_64FC4 = 11; // 64-bit float, 4 channels
  }
  int32 width = 1;  // Width of the image in pixels
  int32 height = 2; // Height of the image in pixels
  bytes data = 3;   // Raw image data in bytes
  MatType type = 4; // Type of the image
}